### ISSUE TITLE
Packages with subdirectories and non-elisp files are not handled properly

### ISSUE THREAD

**Issue by alem0lars** [jauhien/gs-elpa#4]
If a specifies in its recipe the files to be installed, some of them seems to be ignored.
For example the SLIME package from melpa specifies:
```
(slime :repo "slime/slime"
       :fetcher github
       :files ("*.el"
               ("lib" "lib/hyperspec.el")
               "swank"
               "*.lisp"
               "*.asd"
               ("contrib" "contrib/*" (:exclude "contrib/test"))
               "doc/slime.texi"
               "doc/slime.info"
               "doc/dir"
               "ChangeLog"))
```

Which lists the files that should be included.

However when I install the `app-emacs/slime` package I only get these files:
```
slime-autoloads.el
slime.el
slime.elc
slime-tests.el
slime-tests.elc
```

In fact, starting emacs with slime now gives me the error: `Could not open load file: lib/hyperspec`.

**Comment by jauhien** [comment]
Ok, seems to work now. Closing.
